# Generated by Django 5.2.6 on 2025-09-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_sync_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_sync_at',
            field=models.DateTimeField(null=True),
        ),
    ]
