services:
  pgsql:
    image: "postgres:17"
    env_file:
      - ./api/.env
    ports:
      - "${FORWARD_DB_PORT:-54321}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "helix-pgsql:/var/lib/postgresql/data"
    networks:
      - helix
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}",
        ]
      retries: 3
      timeout: 5s
  redis:
    env_file:
      - ./api/.env
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6381}:6379"
    volumes:
      - "helix-redis:/data"
    networks:
      - helix
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  helix:
    driver: bridge
    external: true

volumes:
  helix-pgsql:
    driver: local
  helix-redis:
    driver: local
