# Generated by Django 5.2.6 on 2025-09-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_account_created_at_account_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('sub_account', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('asset_type', models.CharField(db_index=True, max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('underlying_symbol', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('strike_price', models.FloatField()),
                ('put_call', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('effect', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField()),
                ('time', models.DateTimeField(db_index=True)),
                ('trade_date', models.DateTimeField()),
                ('position_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('net_amount', models.FloatField()),
                ('total_fees', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
