# Generated by Django 5.2.6 on 2025-09-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asset_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
