# Generated by Django 5.2.6 on 2025-09-30 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_asset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settlement_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 1, 16, 35, 62652, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='activity_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='put_call',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='strike_price',
            field=models.FloatField(null=True),
        ),
    ]
