# Generated by Django 5.2.6 on 2025-09-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_settlement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset_description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='position_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_date',
            field=models.DateTimeField(null=True),
        ),
    ]
