# Generated by Django 5.2.6 on 2025-09-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_asset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='options_multiplier',
            field=models.FloatField(null=True),
        ),
    ]
