# Generated by Django 5.2.6 on 2025-09-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_options_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_fees',
            field=models.FloatField(default=0),
        ),
    ]
