# Generated by Django 5.2.6 on 2025-09-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_transaction_total_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
