# Generated by Django 5.2.6 on 2025-09-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transaction_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
