# Generated by Django 5.2.6 on 2025-09-29 03:28

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchwabToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedCharField()),
                ('token_type', models.CharField(blank=True, max_length=50)),
                ('expires_in', models.IntegerField(null=True)),
                ('scope', models.TextField(blank=True)),
                ('refresh_token_expires_in', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schwab_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
