# Generated by Django 5.2.6 on 2025-09-29 06:32

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schwab_token', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schwabtoken',
            old_name='refresh_token_expires_in',
            new_name='refresh_token_expires_at',
        ),
        migrations.AddField(
            model_name='schwabtoken',
            name='id_token',
            field=encrypted_model_fields.fields.EncryptedCharField(default=0),
            preserve_default=False,
        ),
    ]
