# Generated by Django 5.2.6 on 2025-09-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "schwab_token",
            "0002_rename_refresh_token_expires_in_schwabtoken_refresh_token_expires_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schwabtoken",
            name="refresh_token_expires_at",
        ),
    ]
