# Generated by Django 5.2.6 on 2025-09-29 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schwab_token', '0003_remove_schwabtoken_refresh_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schwabtoken',
            name='refresh_token_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 6, 42, 43, 499414)),
            preserve_default=False,
        ),
    ]
