# Generated by Django 5.2.6 on 2025-09-29 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schwab_token', '0004_schwabtoken_refresh_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schwabtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 7, 27, 22, 380684, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
